# Generated by Django 6.0.3 on 2026-04-04 12:30

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[blog.validators.validate_forbidden_words],
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[blog.validators.validate_email_domain],
                verbose_name="Email",
            ),
        ),
    ]
